stages:
- name: Crear Imagen
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: jorged/webserver
      registry: index.docker.io
- name: Crear en k8s
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
